# Generated by Django 3.2.5 on 2021-07-16 07:07
from uuid import uuid4

from django.db import migrations

from faker import Faker


faker = Faker()


def create_users_forward(apps, _):
    User = apps.get_model('users', 'User')
    new_users = [
        User(
            username=f'{str(uuid4())}',  # Фейкер не справляется с уникальностью
            email=faker.email(),
            usertime=faker.date_time_this_month(),
        ) for _ in range(1000000)
    ]
    User.objects.bulk_create(new_users)


def create_users_backward(apps, _):
    User = apps.get_model('users', 'User')
    User.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_users_forward, create_users_backward),
    ]
