# Generated by Django 3.2.5 on 2021-07-20 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='notifications', to=settings.AUTH_USER_MODEL,
                                    verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at', 'updated_at'], name='notificatio_created_4cb70a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'email_send', 'push_send'], name='notificatio_user_id_40e53f_idx'),
        ),
    ]
