# Generated by Django 3.2.5 on 2021-07-19 02:33

from django.db import migrations
from django_celery_beat.models import IntervalSchedule, PeriodicTask


def create_periodic_tasks_forward(apps, _):
    schedule, _ = IntervalSchedule.objects.get_or_create(
        every=1,
        period=IntervalSchedule.MINUTES)

    PeriodicTask.objects.create(
        interval=schedule,
        name='Send Notifications',
        task='server.apps.notifications.tasks.send_notifications',
    )

    schedule, _ = IntervalSchedule.objects.get_or_create(
        every=5,
        period=IntervalSchedule.MINUTES)

    PeriodicTask.objects.create(
        interval=schedule,
        name='Clear Notifications',
        task='server.apps.notifications.tasks.clear_notifications',
    )


def create_periodic_tasks_backward(apps, _):
    PeriodicTask.objects.filter(
        name='Send Notifications',
        task='server.apps.notifications.tasks.send_notifications',
    ).delete()

    PeriodicTask.objects.filter(
        name='Clear Notifications',
        task='server.apps.notifications.tasks.clear_notifications',
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(create_periodic_tasks_forward, create_periodic_tasks_backward),
    ]
