# Generated by Django 3.2.5 on 2021-07-19 04:31
from random import randint
from typing import List
from uuid import uuid4

from django.db import migrations
from faker import Faker

faker = Faker()


def spawn_users_forward(apps, _):
    User = apps.get_model('users', 'User')
    users: List[User] = [
        User(
            username=str(uuid4()),
            first_name=faker.first_name(),
            last_name=faker.last_name(),
            user_timedelta=faker.time_delta(randint(1, 9)),
        ) for _ in range(500)
    ]
    User.objects.bulk_create(users)
    User.objects.create(
        username='admin',
        email='admin@gmail.com',
        is_superuser=True,
        is_staff=True,
        user_timedelta=faker.time_delta(randint(1, 9)),
        password='bcrypt_sha256$$2b$12$hbdcP3EDHCHlsfBmV2LZtuQM3Y71.yZYAGg2xtgu12ZLUREkhQKfi',
    )


def spawn_users_backward(apps, _):
    User = apps.get_model('users', 'User')
    User.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(spawn_users_forward, spawn_users_backward),
    ]
